# Generated by Django 2.1.7 on 2019-03-25 22:46

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('username', models.CharField(max_length=60, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('Prof_pic', models.ImageField(blank=True, null=True, upload_to='user_prof_pic', verbose_name='Profile Picture')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date joined')),
                ('works_out', models.CharField(max_length=60, verbose_name='Works out at')),
                ('city', models.CharField(max_length=60, verbose_name='Lives in')),
                ('hometown', models.CharField(max_length=60, verbose_name='Hometown')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('object', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
