# Generated by Django 2.1.7 on 2019-03-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190325_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='album_photos',
            field=models.ImageField(blank=True, null=True, upload_to='album_photos', verbose_name='Album photos'),
        ),
        migrations.AddField(
            model_name='user',
            name='description_card',
            field=models.TextField(blank=True, null=True, verbose_name='Brief Description'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_gym',
            field=models.CharField(default='last gym', max_length=60, verbose_name='Last Gym'),
        ),
    ]
